name: pheasant_meta
description: Metadata to use in The Pheasant Framework.
version: 0.1.0-alpha
repository: https://github.com/pheasantframework/pheasant_meta

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

topics:
  - pheasant
  - pheasant_meta